export default function ReasoningPanel({ lastMessage }) {
  if (!lastMessage || lastMessage.role !== 'assistant') {
    return (
      <div className="reasoning-panel">
        <h2>Why This Route?</h2>
        <p className="reasoning-empty">
          Ask a question to see AI reasoning and explainability (XAI).
        </p>
      </div>
    );
  }

  const msg = lastMessage;

  return (
    <div className={`reasoning-panel ${msg.alert_level === 'emergency' ? 'emergency' : ''}`}>
      <h2>Why This Route?</h2>

      <div className="reasoning-section">
        <h3>AI Reasoning</h3>
        <p className="reasoning-text">{msg.reasoning || 'No reasoning provided.'}</p>
      </div>

      {msg.language_detected && (
        <div className="reasoning-section">
          <h3>Language Detected</h3>
          <span className="language-badge">{msg.language_detected}</span>
        </div>
      )}

      {msg.route && msg.route.length > 0 && (
        <div className="reasoning-section">
          <h3>Recommended Route</h3>
          <ol className="route-list">
            {msg.route.map((step, i) => (
              <li key={i}>
                <span className="route-step">{i + 1}</span>
                {step}
              </li>
            ))}
          </ol>
        </div>
      )}

      <div className="reasoning-section">
        <h3>Alert Level</h3>
        <span className={`alert-badge ${msg.alert_level}`}>
          {msg.alert_level?.toUpperCase()}
        </span>
      </div>

      <div className="reasoning-footer">
        <small>This reasoning is generated by the AI concierge and reflects live stadium conditions.</small>
      </div>
    </div>
  );
}
